version: '3.8'

services:
  rust-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - target_cache:/usr/src/app/target
    working_dir: /usr/src/app
    command: cargo watch -x run

volumes:
  target_cache:
